---
title: "Maxima"
subtitle: "Trying to write readable docs"
author: Ott Toomet
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: 
  html_document:
    highlight: tango
    df_print: kable
    fig_caption: false
    toc: true
    toc_float:
      smooth_scroll: false
    toc_depth: 2
    number_sections: true
---

```{r setup, include=FALSE, cache=FALSE}
options(tibble.width=60, tibble.print_max=7, tibble.print_min=4)
knitr::knit_engines$set(maxima = function(options) {
  code <- paste(options$code, collapse = '\n')
  out  <- system2(
     'maxima', c('-q --batch-string ', shQuote(code)),
     stdout = TRUE
  )
  knitr::engine_output(options, code, out[-1])
                           # remove the first empty line from maxima output
})
knitr::opts_knit$set(aliases=c(h="fig.height"))
knitr::opts_chunk$set(fig.height=100/25.4, 
                      cache=FALSE,
                      message=FALSE)
library(magrittr)
```

# Introduction

Maxima is a nice computer algebra system, however, the docs are rather
hard to read.

A distinct feature of maxima is that each command must end ended with
a semicolon.  The command is not reacted upon until one enters the
semicolon, it feels as if maxima is not working while in fact it is
just waiting for the semincolon, possibly on a new line.


## Online help

The help can be accessed with

```
? <topic>
```
Note space between `?` and the topic, also semicolon is not needed.
Topics can be function names.


# Data Types, Variables, Operators

## Basic Data types

### Constants

* `inf`: (positive) infinity
* `%pi`: 3.14
* `%e`: 2.78
* `%i`: imaginary unit

## Operators:

**^**: exponentiation
```{maxima}
2^5;
```

## Variables

Variables can be assigned as `variable : expression`.  For instance,

```{maxima}
x : 1;
q : 1 - p;
```

Variables can be removed with `kill` function:
```{maxima}
x: 1;
x;
kill(x);
x;
```

## Functions

Functions can be defined with `:=`, and called with just the name
afterwards: 
```{maxima}
f(x, y) := x^2 - y^2;
f(1,2);
```

Function bodies can contain multiple expressions, these should be
separated by `,` (not by semicolon),
potentially as the last character on a line.  If the
function body contains multiple lines, these should be enclosed in
parenthesis. 
So we
can define a function like
```{maxima}
r(x, y) := (x2 : x^2,
 y2 : y^2, 
 (x2 + y2)^0.5);
r(1,1);
```


# Messing with expressions

## Simplification

`expand` opens parenthesis and collects the relevant items:

```{maxima}
e : (a + b)*(a - b);
expand(e);
```

`ratsimp` attempts to simplify the expression into fractions of
polynomials, including inside of non-rational functions.

```{maxima}
e : a^2 - b^2;
ratsimp(e);
```

`express` evaluates unevaluated expression


`float` can convert an expression to fraction:
```{maxima}
sqrt(%pi)/2;
float(sqrt(%pi)/2);
```


## Solving equations

`solve` can solve non-linear equations.  It takes two arguments: a
[vector](#linear-algebra-data-types)
of equations (including named equations), and a vector of
variable names to be solved:
```{maxima}
a: x = 2*y;
b: y = x+1;
solve([a, b], [x, y]);
```



# Linear Algebra

## Data Types {#linear-algebra-data-types}

**Vectors** are created using brackets:
```{maxima}
v : [1, 2, 3];
```
creates a vector _v_ of length three.  Individual elements of vectors
can be extracted with brackers, indexing is 1-based:
```{maxima}
v : [a, b, c];
v[1];
```

**Matrices** can be created using function `matrix` and
wrapping individual lines in brackets:
```{maxima}
matrix([1,2],[3,4]);
```

## Operators {#linear-algebra-operators}

**.** is **inner product**.  For instance:
```{maxima}
u : [u1, u2];
v : [v1, v2];
u.v;
```

**~** is **outer product** (vector product),
defined in _vect_ package: 
```{maxima}
load("vect");
u : [u1, u2, u3];
v : [v1, v2, v3];
express(u ~ v);
```


# Differentiation and integration {#differentiation-integration}

`integrate(f, x)` to compute undetermined integral, `integrate(f, x,
a, b)` to compute determined integral from a to b.  The limits can
contain infinity `inf`:
```{maxima}
phi(x) := 1/sqrt(2*%pi)*exp(-1/2*x^2);
   /* normal density function */
integrate(phi(x), x, -inf, inf); 
```



# Library Functions

* `determinant` (not `det`!)


# Programming

Maxima supports `/* C-style comments */` but not C++-style comments. 
