---
title: "How to create bad photocopy text effect in gimp"
author: Ott Toomet
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: 
  html_document:
    highlight: tango
    df_print: kable
    fig_caption: false
    toc: true
    toc_float:
      smooth_scroll: false
    toc_depth: 2
    number_sections: true
---

I had to replace certain sensitive data in photocopied document in
order to who these to the public.  Proceeded as this (gimp 2.8):

1. Figure out the right font and fontsize.  The font size may differ
quite a bit from the one used in the original document as this
is a function of both original size and scan density.  In my case it
was ~38 points.  Note that _FreeSerif_ fonts are quite close to _Times
New Roman_.
2. Write the text with text tool.  It allows you to correct it later
but it's a bit cumbersome.  I'd do it somewhere on the white
background, just to see if everything is righ.
3. Move the just created text layer in the correct place, over the
original text.  In this way you can easily see if the size is correct,
and fin-adjust the placement.
4. Delete the original text from underneath the new one.  For this,
select the original image layer and operate there.
5. As the filters do not work well on text layer, you have to flatten
the image.  Comverting text layers to ordinary layers will probably do
too.  Use the menu: _Image_ -> _Flatten image_.
6. Now select the new text in the image and apply all the following
filters on this.
7. Add a little bit of _pick_ noise (I used 5%) to make the otherwise
identical letters
slightly different.  It is in _Filters_ -> _Noise_ -> _pick_.
8. Next, pixelize the text: _Filters_ -> _blur_ -> _pixelize_.  The
pixel size depends on how large are the pixels in your original text,
I used 3 points.
9. Apply threshold to transform the intermittent grays into black and
white: _Colors_ -> _threshold_.  I used the threshold value 167.  **This
is the most important step that very much determines how will your
final text look like.**
10. Finally, add some more pick noise, in order to simulate some
small-scale randomness: _Filters_ -> _Noise_ -> _pick_.  I used 5%
amount.
